version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      non-major:
        update-types:
          - minor
          - patch
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
