[workspace]
members = ["miho", "miho_derive"]
exclude = ["mocks"]
resolver = "2"

[workspace.package]
description = "Repository management tools"
homepage = "https://github.com/ferreira-tb/miho"
repository = "https://github.com/ferreira-tb/miho"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["miho", "repository"]
