[package]
name = "miho"
version = "4.0.0"
description = "Repository management tools"
homepage = "https://github.com/ferreira-tb/miho"
repository = "https://github.com/ferreira-tb/miho"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["miho", "repository"]
categories = ["development-tools"]

[dependencies]
anyhow = "1.0"
colored = "2.1"
globset = "0.4"
ignore = "0.4"
inquire = "0.6"
reqwest = { version = "0.11", features = ["json"] }
semver = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["rt-multi-thread"] }

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]

[dependencies.toml]
version = "0.8"
features = ["preserve_order"]
