[package]
name = "miho"
version = "3.0.0"
description = "Easily bump your project version"
homepage = "https://github.com/ferreira-tb/miho"
repository = "https://github.com/ferreira-tb/miho"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
colored = "2"
globset = "0.4"
ignore = "0.4"
inquire = "0.6"
regex = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
