[package]
name = "miho_derive"
version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"
