[package]
name = "miho_derive"
version = "3.7.3"
description = "Repository management tools"
homepage = "https://github.com/ferreira-tb/miho"
repository = "https://github.com/ferreira-tb/miho"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"
