[package]
name = "miho_derive"
version = "4.3.1"

[package.description]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.readme]
workspace = true

[package.keywords]
workspace = true

[package.categories]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.53"
proc-macro2 = "1.0.79"
