[package]
name = "miho_derive"
version = "3.7.10"

[package.description]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.readme]
workspace = true

[package.keywords]
workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"
