[package]
name = "cargo-toml"
version = "2.2.28"

[dependencies]
semver = "1.0.22"
thiserror = "1.0.57"

[dependencies.clap]
version = "4.5.1"
features = ["derive"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]
