[package]
name = "cargo-toml"
version = "2.2.22"

[dependencies]
semver = "1.0"
thiserror = "1.0"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
