[package]
name = "miho"
version = "4.0.0"

[package.description]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.readme]
workspace = true

[package.keywords]
workspace = true

[package.categories]
workspace = true

[dependencies]
anyhow = "1.0"
colored = "2.1"
globset = "0.4"
ignore = "0.4"
inquire = "0.6"
reqwest = { version = "0.11", features = ["json"] }
semver = "1.0"
tokio = { version = "1", features = [] }

[dependencies.miho_derive]
version = "4.0"
path = "../miho_derive"

[dependencies.clap]
version = "4.4"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]

[dependencies.toml]
version = "0.8"
features = ["preserve_order"]
