[package]
name = "miho"
version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0"
colored = "2"
globset = "0.4"
ignore = "0.4"
inquire = "0.6"
regex = "1.10"
thiserror = "1.0"

[dependencies.miho_derive]
version = "3"
path = "../miho_derive"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"
features = ["preserve_order"]

[dependencies.toml]
version = "0.8"
features = ["preserve_order"]
