[package]
name = "miho"
version = "4.3.2"
description = "Repository management tools"
homepage = "https://github.com/ferreira-tb/miho"
repository = "https://github.com/ferreira-tb/miho"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
readme = "../README.md"
edition = "2021"
rust-version = "1.76"
keywords = ["lua", "miho", "repository"]
categories = ["development-tools"]

[dependencies]
anyhow = "1.0.81"
colored = "2.1.0"
crossterm = "0.27.0"
futures = "0.3.30"
globset = "0.4.14"
ignore = "0.4.22"
inquire = "0.7.3"
itertools = "0.12.1"
semver = "1.0.22"
thiserror = "1.0.58"

[dependencies.tabled]
version = "0.15.0"
features = ["ansi"]

[dependencies.reqwest]
version = "0.12.0"
features = ["brotli", "gzip", "json"]

[dependencies.tokio]
version = "1.36.0"
features = ["macros", "process", "rt-multi-thread"]

[dependencies.clap]
version = "4.5.3"
features = ["derive"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.114"
features = ["preserve_order"]

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.toml]
version = "0.8.12"
features = ["preserve_order"]

[dependencies.miho_derive]
version = "4.2"
path = "../miho_derive"
