[package]
name = "miho"
version = "4.1.0"

[dependencies]
anyhow = "1.0"
colored = "2.1"
globset = "0.4"
ignore = "0.4"
inquire = "0.6"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
semver = "1.0"
tabled = { version = "0.15", features = ["ansi"] }
thiserror = "1.0"

[dependencies.reqwest]
version = "0.11"
features = ["brotli", "gzip", "json"]

[dependencies.tokio]
version = "1.36"
features = ["process", "macros", "rt-multi-thread"]

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]

[dependencies.toml]
version = "0.8"
features = ["preserve_order"]

[dependencies.miho_derive]
version = "4.1"
path = "../miho_derive"

[package.description]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.readme]
workspace = true

[package.keywords]
workspace = true

[package.categories]
workspace = true
