name: Publish package

on:
  release:
    types: [created]

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo publish
