name: Publish package

on:
  release:
    types: [created]

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: cargo clippy
      - run: cargo publish -p miho_derive
      - run: cargo publish -p miho
